### ISSUE TITLE
Android studio 升级到最新版本Chipmunk|2021.2.1版本后无法使用

### ISSUE THREAD

**Issue by leifu1107** [lckj686/ArouterHelperKotlin#2]
Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 29, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: wu.seal.tool.jsontokotlin (3.7.3), org.intellij.plugins.markdown (212.5457.16), com.leon.plugin.arouter (1.0.2)

**Comment by sceneren** [comment]
+1

**Comment by lckj686** [comment]
已经兼容提审。可以在release 文件夹里先手动下载2.0.1使用。新旧版本因为使用的idea内核不一样，plugin api不同不会兼容。对应版本对应as使用

**Comment by lckj686** [comment]
已经兼容提审。可以在release 文件夹里先手动下载2.0.1使用。新旧版本因为使用的idea内核不一样，plugin api不同不会兼容。对应版本对应as使用
